spring:
  application:
    name: turbine
server:
  port: 9002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka/
  instance:
    prefer-ip-address: true
turbine:
  #需要收集监控信息的服务名
  app-config: cart-server,order-server,product-server,shipping-server,user-server
  #设置集群名称
  cluster-name-expression: "'mall'"
  #可以让同一主机上的服务通过主机名与端口号的组合进行区分
  combine-host-port: true


