server:
  port: 9000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: admin-server



